config/routes.rb
Rails.application.routes.draw do
  get 'users/show'
  devise_for :users
  root to: 'homes#top'
  get '/posto/hashtag/:name' => 'postos#hashtag'
  #get 'posto/hashtag' => 'posto#hashtag'
  resources :postos
  get 'chat/:id' => 'chats#show', as: 'chat'
  resources :chats, only: [:create]
  resources :users do
      member do
        get :following, :followers
      end
    end
  resources :relationships, only: [:create, :destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/chat.rb
class Chat < ApplicationRecord
    belongs_to :user
    belongs_to :room
end

app/models/hashtag.rb
class Hashtag < ApplicationRecord
  validates :hashname, presence: true, length: { maximum: 99 }
  has_many :hashtag_postos, dependent: :destroy
  has_many :postos, through: :hashtag_postos
end

app/models/hashtag_posto.rb
class HashtagPosto < ApplicationRecord
  belongs_to :posto
  belongs_to :hashtag
  validates  :posto_id, presence: true
  validates  :hashtag_id, presence: true
end

app/models/posto.rb
class Posto < ApplicationRecord
  has_many :hashtag_postos, dependent: :destroy
  has_many :hashtags, through: :hashtag_postos
  belongs_to :user
  
  after_create do
      posto = Posto.find_by(id: id)
      hashtags  = content.scan(/[#＃][\w\p{Han}ぁ-ヶｦ-ﾟー]+/)
      hashtags.uniq.map do |hashtag|
        tag = Hashtag.find_or_create_by(hashname: hashtag.downcase.delete('#'))
        posto.hashtags << tag
      end
  end
 
  before_update do 
      posto = Posto.find_by(id: id)
      posto.hashtags.clear
      hashtags = content.scan(/[#＃][\w\p{Han}ぁ-ヶｦ-ﾟー]+/)
      hashtags.uniq.map do |hashtag|
        tag = Hashtag.find_or_create_by(hashname: hashtag.downcase.delete('#'))
        posto.hashtags << tag
      end
  end
end

app/models/relationship.rb
class Relationship < ApplicationRecord
  belongs_to :user
  belongs_to :follow, class_name: 'User'

  validates :user_id, presence: true
  validates :follow_id, presence: true
end

app/models/room.rb
class Room < ApplicationRecord
  has_many :user_rooms, dependent: :destroy
  has_many :chats, dependent: :destroy
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  
  has_many :postos, dependent: :destroy
  has_many :user_room, dependent: :destroy
  has_many :chat, dependent: :destroy
  
  has_many :relationships, dependent: :destroy
  has_many :followings, through: :relationships, source: :follow
  has_many :reverse_of_relationships, class_name: 'Relationship', foreign_key: 'follow_id', dependent: :destroy
  has_many :followers, through: :reverse_of_relationships, source: :user 
 
  def follow(other_user)
    unless self == other_user
      self.relationships.find_or_create_by(follow_id: other_user.id)
    end
  end

  def unfollow(other_user)
    relationship = self.relationships.find_by(follow_id: other_user.id)
    relationship.destroy if relationship
  end

  def following?(other_user)
    self.followings.include?(other_user)
  end
  
  attachment :profile_image
end

app/models/user_room.rb
class UserRoom < ApplicationRecord
    belongs_to :user
    belongs_to :room
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

#   before_action :authenticate_user!, only: [:top, :index, :show]
  before_action :configure_permitted_parameters, if: :devise_controller?

  def after_sign_in_path_for(resource)
    postos_path
  end

  def after_sign_out_path_for(resource)
    root_path
  end
  
  
  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name, :email])
  end
  
protect_from_forgery with: :exception
end

app/controllers/chats_controller.rb
class ChatsController < ApplicationController
    def show
      @user = User.find(params[:id])  
      rooms = current_user.user_room.pluck(:room_id)
      user_rooms = UserRoom.find_by(user_id: @user.id, room_id: rooms)
      
      unless user_rooms.nil?
          @room = user_rooms.room
      else
          @room = Room.new
          @room.save
          UserRoom.create(user_id: current_user.id, room_id: @room.id)
          UserRoom.create(user_id: @user.id, room_id: @room.id)
      end
      @chats = @room.chats
      @chat = Chat.new(room_id: @room.id)
    end
    
    def create
      @chat = current_user.chat.new(chat_params)
      @chat.save
      redirect_to request.referer
    end
    
    private
    def chat_params
      params.require(:chat).permit(:message, :room_id)
    end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
    
    def top
    end
    
end

app/controllers/postos_controller.rb
class PostosController < ApplicationController
  before_action :authenticate_user!, except: [:hashtag, :index]


  def hashtag
    @user = current_user
    @tag = Hashtag.find_by(hashname: params[:name])
    @posto  = @tag.postos.page(params[:page])
    @users = User.all
  end
  
  def index
    @postos = Posto.page(params[:page]).reverse_order
    @tags = Hashtag.all
    @search = Posto.ransack(params[:q])
    @results = @search.result
    @check = params[:q]
  end
  
  def new
    @posto = Posto.new
  end
  
  def show
    @posto = Posto.find(params[:id])
  end
  
  def create
    @posto = Posto.new(posto_params)
    @posto.user_id = current_user.id
    if @posto.save
      redirect_to postos_path
    else
      render index
    end
  end
  
  def destroy
    @posto = Posto.find(params[:id])
    if @posto.destroy
       redirect_to postos_path
    else render postos_path
    end
  end
  
  private
  
  def posto_params
    params.require(:posto).permit(:content, :hashtag_ids) 
  end
  
end

app/controllers/relationships_controller.rb
class RelationshipsController < ApplicationController

  def create
    user = User.find(params[:follow_id])
    current_user.follow(user)
    redirect_to users_path
  end

  def destroy
    user = User.find(params[:follow_id])
    current_user.unfollow(user)
    redirect_to users_path
  end
  
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!, except: [:index]
  
  def index
    @users = User.all
  end
  
  def show
    @user = User.find(params[:id])
    @postos = @user.postos
  end
  
  def edit
    @user = current_user
  end
  
  def update
    @user = current_user
    if @user.update(user_params)
      redirect_to postos_path, notice: "変更しました"
    else render :edit
    end
  end
  
  def following
      @user  = User.find(params[:id])
      @users = @user.following
      render users_path
  end

  def followers
    @user  = User.find(params[:id])
    @users = @user.followers
    render users_path
  end
    
  def user_params
    params.require(:user).permit(:name, :introduction, :profile_image)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/chats_helper.rb
module ChatsHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/postos_helper.rb
module PostosHelper
  def render_with_hashtags(content)
    content.gsub(/[#＃][\w\p{Han}ぁ-ヶｦ-ﾟー]+/){|word| link_to word, "/posto/hashtag/#{word.delete("#")}"}.html_safe
  end 
end

app/helpers/relationships_helper.rb
module RelationshipsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/chats/show.html.erb
<%= render 'postos/posto' %>
<div class="container">
  <div class="row">
    <div class="col-5 mx-auto heading-img"><%= @user.name %>と<%= current_user.name %>のチャット部屋</div>
  </div>
  <%= form_with model: @chat, class: "row g-2 offset-md-2 my-3 form-group form-inline", local: true do |f| %>
    <%= f.text_field :message, class: "form-control col-8",  placeholder: "メッセージを送ってみよう" %>
    <%= f.hidden_field :room_id %>
    <%= f.submit '送信する', class: "btn btn-primary col-2 mx-2" %>
  <% end %>
  <% @chats.each do |chat| %>
    <div class="row g-2 offset-md-2">
      <div class="col-1 my-3">
        <%= link_to user_path(chat.user_id) do %>
          <%= attachment_image_tag chat.user, :profile_image, :fill, 50, 50, fallback: "no_image.jpg", size:'50x50', class: "img" %>
        <% end %>
      </div>
      <div class="col-8 my-2 rounded-3 border border-info">
        <%= chat.message %>
      </div>
    </div>
  <% end %>
</div>

app/views/homes/top.html.erb
<div class="container">
    <div class="row">
      <h1 class="mx-auto p-2">げむチャを始めてみよう！</h1>
    </div>
    <div class="row">
      <% if user_signed_in? %>
        <div class="col">
          <%= link_to "みてみる", postos_path, class: "fas fa-bolt btn btn-outline-success btn-block" %>
        </div>
        <div class="col">
          <%= link_to "ログアウト", destroy_user_session_path,method: :delete, class: "fas fa-sign-out-alt btn btn-outline-info btn-block" %>
        </div>
      <% else %>
        <div class="col">
          <%= link_to "みてみる", postos_path, class: "fas fa-bolt btn btn-outline-success btn-block" %>
        </div>
        <div class="col">
          <%= link_to "ログイン", new_user_session_path, class: "fas fa-sign-in-alt btn btn-outline-primary btn-block" %>
        </div>
        <div class="col">
          <%= link_to "新規登録", new_user_registration_path, class: "far fa-address-card btn btn-outline-secondary btn-block" %>
        </div>
      <% end %>
    </div>
    <%= image_tag 'samune.jpg', class: "img-fluid", alt: "ホーム画像" %>
</div>

app/views/postos/_posto.html.erb
<div class="container">
    <div class="row mx-auto">
        <%= link_to "back", 'javascript:history.back()', class: "fas fa-chevron-left btn btn-outline-secondary my-3 btn-lg col-3" %>
        <div class="col"></div>
        <%= link_to "投稿する", new_posto_path, class: "far fa-paper-plane btn btn-outline-info my-3 btn-lg col-3" %>

  </div>
</div>

app/views/postos/hashtag.html.erb
<%= render 'postos/posto' %>
 <div class="container">
   <div class="row">
    <div class="col-5 mx-auto heading-img">
      #<%= @tag.hashname %>　のいちらん
    </div>
   </div>
   <% @posto.each do |posto| %>
    <div class="container mx-auto rounded-5 border border-info post m-3">
      <div class="row">
        <div class="col-1 m-3">
          <div class="mx-2"><%= posto.user.name %></div>
          <%= link_to user_path(posto.user_id) do %>
            <%= attachment_image_tag posto.user, :profile_image, :fill, 80, 80, fallback: "no_image.jpg", size:'80x80', class: "img" %>
          <% end %>
        </div>
        <div class="col my-4 mx-4 post-text">
          <%= link_to posto_path(posto) do %>
            <%= render_with_hashtags(posto.content) %>
          <% end %>
        </div>
      </div>
    </div>
  <% end %>
 </div>
  <%= paginate @posto %>

app/views/postos/index.html.erb
<%= render 'postos/posto' %>
<div class="container">
  <%= search_form_for @search, class: "row g-2 offset-md-2 my-3 form-group form-inline", local: true do |f| %>
    <%= f.search_field :content_cont,required: true, class: "form-control col-8", placeholder: "投稿の検索ができるよ" %>
    <%= f.submit '検索', class: "btn btn-outline-primary col-2 mx-2"%>
  <% end %>
  <% if @check.present? %>
    <div class="row offset-md-2">
      <p>検索結果</p>
    </div>
    <% @results.each do |kekka| %>
    <div class="row mx-auto toukou">
      <%= link_to user_path(kekka.user_id) do %>
        <%= attachment_image_tag kekka.user, :profile_image, :fill, 40, 40, fallback: "no_image.jpg", size:'40x40', class: "img" %>
      <% end %>
      <%= link_to posto_path(kekka.id) do %>
        <%= render_with_hashtags(kekka.content) %>
      <% end %>
    </div>
    <% end %>
  <% end %>
  <div class="col-5 mx-auto heading-img">
    使われているタグ一覧
  </div>
  <div class="row mx-auto">
    <div class="col">
      <% @tags.each do |tag| %>
        <%= link_to "/posto/hashtag/#{tag.hashname}" do %>
          #<%= tag.hashname %>
        <% end %>
      <% end %>
    </div>
  </div>
</div>
<div class="col-5 mx-auto heading-img">
  投稿一覧
</div>
<% @postos.each do |posto| %>
  <div class="container mx-auto rounded-5 border border-info m-3 post profile-toukou">
    <div class="row">
      <div class="col-1 m-3">
        <div class="mx-2"><%= posto.user.name %></div>
        <%= link_to user_path(posto.user_id) do %>
          <%= attachment_image_tag posto.user, :profile_image, :fill, 80, 80, fallback: "no_image.jpg", size:'80x80', class: "img" %>
        <% end %>
      </div>
      <div class="col my-4 mx-4 post-text">
        <%= link_to posto_path(posto) do %>
          <%= render_with_hashtags(posto.content) %>
        <% end %>
      </div>
    </div>
  </div>
<% end %>
<%= paginate @postos %>

app/views/postos/new.html.erb
<div class="container">
  <%= link_to "←back", postos_path, class: "btn btn-outline-secondary m-3" %>
  <%= form_with model: @posto, local: true do |f| %>
    <%= f.label :content, "投稿内容" %>
    <%= f.text_area :content, class: "form-control m-3", rows: 3, placeholder: "ここに内容を書いてね" %>
    <%= f.submit '投稿', class: "btn btn-outline-primary m-3" %>
  <% end %>
</div>

app/views/postos/show.html.erb
<%= render 'postos/posto' %>
<div class="container">
  <div class="row">
    <div class="col-5 mx-auto heading-img">
      Posto show
    </div>
  </div>
  <div class="container mx-auto rounded-5 border border-info post m-3">
    <div class="row">
      <div class="col-1 m-3">
        <div class="mx-2">
          <%= @posto.user.name %>
        </div>
        <%= link_to user_path(@posto.user_id) do %>
          <%= attachment_image_tag @posto.user, :profile_image, :fill, 80, 80, fallback: "no_image.jpg", size:'80x80', class: "img" %>
        <% end %>
      </div>
      <div class="col my-4 mx-4 post-text">
        <%= link_to posto_path(@posto) do %>
          <%= render_with_hashtags(@posto.content) %>
        <% end %>
      </div>
      <div class="col-2 align-self-end my-4">
        <% if @posto.user_id == current_user.id %>
          <%= link_to "削除", posto_path(@posto), method: :delete, data: {confirm: "本当に消しますか？"}, class: "btn btn-danger" %>
        <% end %>
      </div>
    </div>
  </div>
      
  <div class="profile row rounded border border-info toukou mx-auto my-3">
    <table class="table">
      <tbody>
        <tr>
          <th>
            <%= link_to user_path(@posto.user_id) do %>
              <%= attachment_image_tag @posto.user, :profile_image, :fill, 100, 100, fallback: "no_image.jpg", size: '100x100', class: "img" %>
            <% end %>
          </th>
          <th></th>
        </tr>
        <tr>
          <th>name</th>
          <th><%= @posto.user.name %></th>
        </tr>
        <tr>
          <th>introduction</th>
          <th><%= @posto.user.introduction %></th>
        </tr>
        <tr>
          <th>follow数</th>
          <th>あとで実装する！！</th>
          <!--<th>%= @user.followings.count %>人</th>-->
        </tr>
        <tr>
          <th>follower数</th>
          <th>aa</th>
          <!--<th>%= @user.followers.count %>人</th>-->
        </tr>
        <tr>
          <th>
            <% if @posto.user == current_user %>
              <%= link_to "プロフィール編集", edit_user_path(current_user), class: "btn btn-success" %>
            <% end %>
            <% if current_user != @posto.user %>
              <%= link_to 'chatを始める', chat_path(@posto.user.id), class: "btn btn-info" %>
            <% end %>
          </th>
          <th></th>
        </tr>
      </tbody>
    </table>
  </div>
</div>

app/views/relationships/_follow_button.html.erb
<% unless current_user == user %>
  <% if current_user.following?(user) %>
    <%= form_with model: current_user.relationships.find_by(follow_id: user.id), method: :delete, local: true do |f| %>
      <%= hidden_field_tag :follow_id, user.id %>
      <%= f.submit 'Unfollow', class: 'btn btn-danger btn-block' %>
    <% end %>
  <% else %>
    <%= form_with model: current_user.relationships.build, local: true do |f| %>
      <%= hidden_field_tag :follow_id, user.id %>
      <%= f.submit 'Follow', class: 'btn btn-primary btn-block' %>
    <% end %>
  <% end %>
<% end %>

app/views/users/edit.html.erb
<%= render 'postos/posto' %>
<p id="notice"><% notice %></p>
<div class="container">
  <div class="row">
    <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
      <h2>User info</h2>
        <div class="error-m">
          <% if @user.errors.any? %>
            <h2><%= @user.errors.count %>errors prohibited this obj from being saved:</h2>
            <ul>
              <% @user.errors.full_messages.each do |message| %>
                <li><%= message %></li>
              <% end %>
            </ul>
          <% end %>
        </div>
        <%= form_with model: @user, local:true do |f| %>
        <div class="form-group">
          <div class="field_with_errors">
          <%= f.label :name, 'Name' %>
          <%= f.text_field :name, class: "form-control name" %>
          </div>
        </div>
        <div class="form-group">
          <div class="field_with_errors">
          <%= f.label :profile_image, 'Image' %>
          <%= f.attachment_field :profile_image %>
          </div>
        </div>
        <div class="form-group">
          <div class="field_with_errors">
          <%= f.label :introduction, 'Introduction' %>
          <%= f.text_area :introduction, rows: 5, class: "form-control introduction" %>
          </div>
        </div>
        <div class="form-group">
           <%= f.submit "Update User", class: "btn btn-secondary" %>
　　    <% end %>
      　</div>
    </div><!--col-sm-12-->
  </div><!--row-->
</div><!--container-->

app/views/users/index.html.erb
<%= render 'postos/posto' %>
<%= flash[:alert] %>
<div class-"container">
  <div class="row">
    <div class="col-5 mx-auto heading-img">
      みんな一覧
    </div>
  </div>
  <p class="text-center">あとでフォロー機能つける！</p>
  <!--% if current_user != user %>-->
    <!--% if current_user.following?(user) %>-->
      <!--%= button_to 'フォロー解除', relationship_path(current_user.relationships.find_by(follower: user)), method: :delete %>-->
    <!--% else %>-->
    <!--%= button_to 'フォロー', relationships_path(follower: user) %>-->
    <!--% end %>-->
  <!--% end %>-->
    <% @users.each do |user| %>
    <div class="container mx-auto rounded-5 border border-info m-3 post profile-toukou">
      <div class="row">
        <div class="col-1 m-3">
          <div class="mx-2">
            <%= link_to user.name, user_path(user) %>
          </div>
          <%= link_to user_path(user) do %>
            <%= attachment_image_tag user, :profile_image, :fill, 80, 80, fallback: "no_image.jpg", size:'80x80', class: "img" %>
          <% end %>
        </div>
        <div class="col my-4 mx-4 post-text">
          <%= user.introduction %>
          <%= render 'relationships/follow_button', user: user %> 
        </div>
      </div>
    </div>
    <% end %>

app/views/users/show.html.erb
<%= render 'postos/posto' %>
<%= flash[:success] %>
<%= flash[:alert] %>
<div class-"container">
  <div class="row">
    <div class="col-5 mx-auto heading-img">
      ぷろふぃーる
    </div>
  </div>
  <div class="profile row rounded border border-info toukou mx-auto my-3">
    <table class="table">
      <tbody>
        <tr>
          <th><%= attachment_image_tag @user, :profile_image, :fill, 100, 100, fallback: "no_image.jpg", size: '100x100', class: "img" %></th>
          <th></th>
        </tr>
        <tr>
          <th>name</th>
          <th><%= @user.name %></th>
        </tr>
        <tr>
          <th>introduction</th>
          <th><%= @user.introduction %></th>
        </tr>
        <tr>
          <th>follow数</th>

          <th>あとで実装する！！</th>
          <!--<th>%= @user.followings.count %>人</th>-->
        </tr>
        <tr>
          <th>follower数</th>
          <th>aa</th>
          <!--<th>%= @user.followers.count %>人</th>-->
        </tr>
        <tr>
          <th>
            <% if @user == current_user %>
              <%= link_to "プロフィール編集", edit_user_path(current_user), class: "btn btn-success" %>
            <% end %>
            <% if current_user != @user %>
              <%= link_to 'chatを始める', chat_path(@user.id), class: "btn btn-info"%>
            <% end %>
            <%= render 'relationships/follow_button', user: @user %>
          </th>
          <th></th>
        </tr>
      </tbody>
    </table>
  </div>
  <div class="col-5 mx-auto heading-img">投稿一覧</div>
    
    <% @postos.each do |posto| %>
    <div class="container mx-auto rounded-5 border border-info m-3 post profile-toukou">
      <div class="row">
        <div class="col-1 m-3">
          <div class="mx-2">
            <%= posto.user.name %>
          </div>
          <%= link_to user_path(posto.user_id) do %>
            <%= attachment_image_tag posto.user, :profile_image, :fill, 80, 80, fallback: "no_image.jpg", size:'80x80', class: "img" %>
          <% end %>
        </div>
        <div class="col my-4 mx-4 post-text">
          <%= link_to posto_path(posto) do %>
            <%= render_with_hashtags(posto.content) %>
          <% end %>
        </div>
        <div class="col-2 align-self-end my-4">
          <% if posto.user_id == current_user.id %>
            <%= link_to "削除", posto_path(posto), method: :delete, data: {confirm: "本当に消しますか？"}, class: "btn btn-danger" %>
          <% end %>
        </div>
      </div>
    </div>
    <% end %>
  
  </div>
  </div>